language: python
python:
- '3.6'
- '3.7'
dist: xenial
install:
- pip install pipenv
- pipenv install --dev
script:
- python -m pytest --cov=thedropin
- pylint **/*.py
after_success:
- codecov
deploy:
- provider: pypi
  user: digitalvapor
  skip_cleanup: true
  password:
    secure: 0Q3c7CdbU4CdDVMBeSHgQq2VA+eSUzSGH5WjR88RbOYyRtMIgnUgfsxA6xU9CFK33wA75JZvLmQukow/xPMCkkry5DHwUOAws+rjXUwvWMM0bywnANqvsa+RNMZCI84gWDRe0mS+C+Vt5GYIwPK9ZegiWGwqQfZ5O8VyDBvrZ0YgOT2lrcWUJTmo+NcDIpJLwsBT25xejqnZ2l6L7wrNtI0+5QmAlUCbdKWYAuzr0lY/OJGAFDvbtgBaJuhEOXKTEdoHBwIX2xiOJ1MGHtulIcVfbnebpQSXWn0mJMbezjdqaXew7bBlEIS7OKdGboWTWIB2hgb+i0OyM757qE5d/nKn7G+VkpfZyr5wkZdhOd5rY2LSr4FDJuDDO7TvqF6CFZwOZi1PQiKOyE0tcM93f9VtFQeU1wdg6KW8H/hy6TRXh3osH3MOjYTejQqTHMqKmiKG+o4WnN758Asj/6oKSDr6G567CBby/3tsWwlbE8ZlTEocuBoHm47V/NF0oLxSswnNm82gd1YeCUiReDDLZGNXWqt8/hV2vcwkKbagk0CmSOY1YHc37MVGZhzzZ36S2CSlx8yCgs6UfWYNUaXZ3Q0uPBWs4/4teWYHfIPHQ3SbsTFOjKOkzY1gHqccCYZnvAx9qdr9clHMZfq/MhzB5ZyTAsQUab1OlEttwTlDuoQ=
  on:
    tags: true
