language: python
python:
- '3.6'
- '3.7'
dist: xenial
install:
- pip install pipenv
- pipenv install --dev
script:
- python -m pytest --cov=thedropin
- pylint **/*.py
after_success:
- codecov
deploy:
- provider: pypi
  user: digitalvapor
  skip_cleanup: true
  password:
    secure: "qiVZMAA28gFILVQqKTyfEP4qNSxF6YKNaS5C7TqvxWdkoUAmyeQW3eumGaeDS+te95653WeH57Uev1gyiznegonNW7kbMBwDR9+cno1n50w1v9CdVqM20kYZzaVzt7m1RlbE82BOGnFwYRUxvTCBU4a5QWJvMChi3zCXrYCmaC2ZwzE6BGs6saoSnp637VqtQAb1eFPKDRD40bGyuniSpqmC3rVofbdBLJG/AeNo/FNoR0fyRSboMKmAXu7Jossyou8ssspVyyEMa3fBnR8hoPbUppNpHcXrIgNx6rv042mOWrR/DHIYT29t/vA/qYTRTxLeFUXnSrv7GrOfdFohFr3+CwfIDwGRZpfhI7E9LvbdCcTD8FWx/5HA/v0zDnMvpzWt/ysMSrj8gAWO1bIQqkT1gw2kxDzCef9iRZOpdME8Qjl+gNwqlIuzOMtPEv8QKb0Hw4LZaRr+k+XNOC4iOSDoUa/3R8z553OOwoD7efuU/CJ95ChN6HnNV7HMaZkfyItCugGwVbcddquRerHD1ltBK+XL1XQ0ZRcy0pMYXqooaFZnNbdVKx8eLvBMl9yO1v4Mr3KUY2R7WZFjAjtlsBW6hAt3Gz2fDNM9AJ3ehq+H7hSnzMSjJcDt+DoQvwA+WoU8kIuf/VuLXutAk/zxIBvggTce+cjBetj33ugLzIE="
  on:
    tags: true
