language: python
python:
- '3.6'
- '3.7'
dist: xenial
install:
- pip install pipenv
- pipenv install --dev
script:
- python -m pytest --cov=thedropin
- pylint **/*.py
after_success:
- codecov
deploy:
- provider: pypi
  user: digitalvapor
  skip_cleanup: true
  password:
    secure: IF5n6VPXYRMduKit6eHbb0g6Y5XvyS3HLnC5ZE47wGMmvdRUHt1WyL3F8oynuAqpvZnVwiwt5dyYSsFiXq8RhuuY8tMPtN6amlRsDvd9t1+Y91PDanzcean+1RK36wt0EvwvVUI71csq77htW/fhbYwvIqFcOooBUoCm99v0ikKPX2LOWXOQo/eH3CBO8kNsBpU8sOkLiS2TD8eWk4LPkwadxopV7n5FDJyGtd4MCk4ckv2WjHHyw+f+xebJk3dR+FTafeyL7IFcFPfYKMU2ruWI0DSyox5Jb+gRhREf0I75tSvSmksw2QhWsMuan+XAVNU2CIIW9AvqRQ9C/EOYxFLmYY8vJhzbLZaQn8dsX8suTfSTFGH/iNA35b/B1/9B8TU87rYBdpnxzcQ6blGu0SPHy/eVt9IdKbCdpRN5PT/GuY/eSQSF4EoospwpjoTDWS4ui1hBdnnbK60M2yhVvtIqsj8qTmwok7lUNu9yQsjxl9AwKo6eMBwGKhgXskv9sdLl0Q8QpDxb8TpH5Lj0loenDCM8/bwVamljKPX4NFrlckeSLDL0ZxMa3NyO3eTe0aMVjuTkJNmEWIFj0gZbkESQKQLKW/EZoUbm5uUNveKCBE6LMBKA7xmZDoL/F/8Kd87beFmMC54+BWrCOKyffNc12U3NKyBjXmSAgEWUSEc=
  on:
    tags: true
