language: python
python:
- '3.6'
- '3.7'
dist: xenial
install:
- pip install pipenv
- pipenv install --dev
script:
- python -m pytest --cov=thedropin
- pylint **/*.py
after_success:
- codecov
deploy:
- provider: pypi
  user: digitalvapor
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: "piPVWRKlV6u8QrMEpjz42Y0F8/0j3XqzmYpjpp8YbGfXlbBp/GKf6LDGQ8rrmemGnCRyb7KStK9I/1Pvg/Jcz82opk4rCOJ9sf0PA7LQNzobveZnoquoGKNLp8jVem2htHm3wZfUH8ikVL6X4wR006mutRw0qQcxDl0d6TqgwenvDaqxmWvTo8o535v7lo/D8u3N1WqL3UFWCf2XrKML5OcjhF1eyPTumRpj422fWqLFTt3x0XaUCP4uJp2IRC8oRov3IgTTJYh2ZDX35JZe+OSgskQZvVjO6voeY49Tuqdm/Sr6QnvNHfLrTNFLLYDGNxZHw7jo13hv1EDS5AQ4diWI32JbwY8ClgvA2QZ0Rhj1fqjDsM17oEsx6xjUv3UGVWbnvx+bbfWErI93dCA61NQrRfnfCHYLdGTbZd5urBNdoA8UdcTcjvbTwThlt6MbYkWMCSlyKLOu0/1ZilU4ZMtGPTz6dnmV9suphrIkwG8fRbg0Edwn5tVrVUnrXSLm2wuLG1j4rO+njAjcr4zB1HKOrTd8xA+CmJBP5BvKbHs8T2SFdQsenSGOHIFtgUKndbCjrFnZvoASz/UDZRKfA2ndv7iA1bpYJA2HqWXbFdml16xcu9+LlW7oSNjkt1EwalIxhmTsUtByHMkO2yFJvCAAvVMboIv+sKRebczws1g="
